### ISSUE TITLE
Error: Check your network code and permissions. Not able to successfully access your service account

### ISSUE THREAD

**Issue by scorti80** [prebid/line-item-manager#113]
* line-item-manager version:0.2.5
* Python version:pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
* Operating System:CentOS Linux release 7.9.2009 (Core)

### Description

After configuring a new YML, we were testing with --dry-run to make sure all was ok. 
but we keep getting the error:
Error: Check your network code and permissions. Not able to successfully access your service account

Note:We use the same json key file for multiple AdsManager API (reporting for example) all is working correctly.

### What I Did
line_item_manager create AdPone_config.yml -v --dry-run --private-key-file /home/adx.exmarketplace.com/vendor/googleads/googleads-php-lib/hotelskanner-57a4e902aa62.json --network-code 42150330 --network-name ExMarketPlace --bidder-code adpone

[AdPone_config.zip](https://github.com/prebid/line-item-manager/files/9382380/AdPone_config.zip)

we have used line-item-manager half a dozen times, always working perfectly. last time was in may. no issues. 
cant figure out what has changed since that could give this authentication error.

**Comment by scorti80** [comment]
> 

we also tried setting up a completely new Service Account, setup looks good in admanager. 
still getting the same error

![Firefox_Screenshot_2022-08-19T17-37-03 515Z](https://user-images.githubusercontent.com/88330557/185676087-f3ae7e44-7d47-46b0-a2ff-d4521bb5b49d.png)

**Comment by dshore** [comment]
I am reviewing error message for why this may be happening for you, but I will note that python 3.6 is EOL and is no longer supported, see [Python EOL](https://endoflife.date/python).

**Comment by dshore** [comment]
also note that your pip version is quite old, current is 22.2.2

**Comment by dshore** [comment]
Also, are you getting any other errors or warnings that you can provide since the message you are seeing is only shown when a googleads.errors.GoogleAdsError exception is raised:
https://github.com/prebid/line-item-manager/blob/master/line_item_manager/cli.py#L108-L110

For example something like this:

`WARNING:googleads.soap:Error summary: {'faultMessage': "[AuthenticationError.NETWORK_NOT_FOUND @ ; trigger:'421503330']", 'requestId': '3e8850379429d80a9458103487830c8b', 'responseTime': '46', 'serviceName': 'NetworkService', 'methodName': 'getCurrentNetwork'}`

**Comment by scorti80** [comment]
we have put in a request for updating pip and python. 

meanwhile, this is the full output that we receive:

VERBOSE1:line_item_manager.gam_config:targeting:
{}
VERBOSE1:line_item_manager.gam_config:rate:
{'currency': 'USD', 'granularity': {'type': 'dense'}}
Usage: line_item_manager create [OPTIONS] CONFIGFILE
Try 'line_item_manager create --help' for help.

Error: Check your network code and permissions. Not able to successfully access your service account

**Comment by dshore** [comment]
While you are waiting for upgrades you can try to get this library working which is used by the line-item-manager:
https://github.com/googleads/googleads-python-lib/blob/master/examples/ad_manager/v202208/network_service/get_current_network.py

You will need to copy and configure the following to specify network_code and path_to_private_key_file:
https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml

**Comment by scorti80** [comment]
not showing any errors.  here is the output from execution:

python3 get_current_network.py
Current network has network code '42150330' and display name 'ExMarketPlace'.

**Comment by dshore** [comment]
I replicated your problem with Python 3.6 and v0.2.5.  The problem is not your credentials (the error message is misleading) but the Google Ad Manager API version is hard coded as 'v202105' in the v0.2.5 version you are using:
https://github.com/prebid/line-item-manager/blob/v0.2.5/line_item_manager/conf.d/settings.yml#L16

And v202105 has been deprecated:
https://developers.google.com/ad-manager/api/deprecation

Upgrading to the latest line-item-manager code should fix your problem, but as noted it does require Python3.7+.  You could change the version in your own fork, but it has not been tested.

Action Items:

1. Code should be fixed to show the proper error message, in this case which is that the GAM API version is not supported.  I will open a new issue.
2. I could push the GAM API version into the config template so users can override the default, but this will be difficult to support and test, as the line-item-manager will have to support all active versions.

**Comment by scorti80** [comment]
Excellent, thank you for this. am still waiting for the python3.7 upgrade, and will test again.

**Comment by scorti80** [comment]
Confirm issue fixed with updated Python and library. 
Thank you

**Comment by diecastben** [comment]
Hi, I'm experiencing the same issue as the original post describes.
For me I ran a few successful line item manager "jobs" and suddenly this error started to show without any change from my end to the configuration or service key JSON files.

This is the prompt I use:
`line_item_manager create someName.yml --network-code 2161****323 -k C:\Users\b.f\someName.json --single-order`

I'm using line item manager version 0.2.12
with version  Python 3.9.10
with version  pip 22.3.1

The authentication details are 100% correct. 
and yet I all of a sudden started to repetaidly receive the following error:
`Error: Check your private key file. Not able to successfully access your service account`
